import Workflow from "../models/workflow.model.js";
import { generateAIResponse } from "./ai.service.js";

export const processChat = async (message) => {
  const workflow = await Workflow.findOne();

  const agentTypes =
    workflow?.agents.map(a => a.type).join(", ") ||
    "research, summarizer";

  const systemPrompt = `
    You are an AI workflow engine.

    The workflow contains the following agents:
    ${agentTypes}

    You must simulate execution in this STRICT format shown in the below example:

    AI: <One short professional introductory sentence>

    (blank line)

    1) Research:
    <Detailed explanation generated by research agent>

    (blank line)

    2) Summary:
    <Concise professional summary generated by summarizer agent>

    Rules:
    - Always add proper spacing for each agent and highlight the agent name in bold.
    - Always add a line break before starting new agent.
    - Always follow this exact structure.
    - Always include proper spacing.
    - Do NOT explain what you are doing.
    - Do NOT narrate steps.
    - Only return structured output.
  `;

  const finalPrompt = `
    User Request:
    ${message}
  `;

  const aiResponse = await generateAIResponse(
    systemPrompt + "\n\n" + finalPrompt
  );

  return aiResponse;
};
